User creation routes
IncluesionIO/incluesionIO-api pull request #13
Opened 2022-09-15 16:55 UTC by ZiadMalik1

Email Field and User Creation Routes Created

2022-09-15 22:33 UTC, DanielTejeda98 requested changes

2022-09-15 22:33 UTC, DanielTejeda98 commented on routes/admin.route.js
> +    body("email").not().isEmpty().withMessage("Email cannot be empty"),
We can use .isEmail() as the validator here
`body("email").normalizeEmail().isEmail().withMessage("Email cannot be empty")`

2022-09-15 22:33 UTC, DanielTejeda98 commented on routes/user.route.js
> +    body("email").not().isEmpty().withMessage("Email cannot be empty"),
We can use .isEmail() as the validator here
`body("email").normalizeEmail().isEmail().withMessage("Email cannot be empty")`

2022-09-16 02:39 UTC, ZiadMalik1 reviewed
Changes Completed

2022-09-16 15:22 UTC, DanielTejeda98 submitted a review, later dismissed

2022-09-16 15:24 UTC, DanielTejeda98 approved these changes

2022-09-16 15:24 UTC, merged